## algoritmo usando data desde json

In [75]:
# librerias

import json
import numpy as np

#### leer json

In [10]:
# leer json

with open('body.json', 'r', encoding='utf-8') as file:
    datos = json.load(file)

datos_estudiantes = datos['estudiantes']
datos_desafios = datos['desafios']
datos_max_por_carrera = datos['carreras']



#### creacion del ambiente

In [71]:
# matrices (seleccion y preferencias)
# matriz de seleccion
matriz_asignaciones = [[0 for _ in range(len(datos_desafios))] for _ in range(len(datos_estudiantes))]
# matriz de preferencias
matriz_preferencias = [[0 for _ in range(len(datos_desafios))] for _ in range (len(datos_estudiantes))]

for i, estudiante in enumerate(datos_estudiantes):
    estudiante['ID'] = i + 1

for i, carrera in enumerate(datos_max_por_carrera):
    carrera['ID'] = i + 1

"""
for estudiante in datos_estudiantes:
    # Buscar el ID de la carrera
    id_carrera = next((carrera['ID'] for carrera in datos_max_por_carrera if carrera['Nombre'] == estudiante['Carrera']), None)
"""

for i, estudiante in enumerate(datos_estudiantes):
    for prioridad, postulacion in enumerate(estudiante['Postulaciones']):
        for j, desafio in enumerate(datos_desafios):
            if desafio['Titulo'] == postulacion:
                matriz_preferencias[i][j] = prioridad + 1

print("Nombres                                      ID     carrera                                Matriz de preferencias")
print("\n")
for i, estudiante in enumerate(datos_estudiantes): 
    print(f"{estudiante['Nombre']:<46}", end="")
    #print(f"{estudiante['ID']:<5} | {estudiante['Carrera']:<35} | {id_carrera:<10}", end=" ")
    print(f"{estudiante['ID']:<5} | {estudiante['Carrera']:<35}", end=" ")
    print(f"|  {'  '.join(map(str, matriz_preferencias[i]))}") 
    

Nombres                                      ID     carrera                                Matriz de preferencias


Matias Ignacio Ayala Nanjari                  1     | Ingeniería Civil Telemática         |  1  0  0  0  0  0  0  0  3  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  2  0  0  0  0  0
Ignacio Andrés Araya Salinas                  2     | Ingeniería Civil Telemática         |  1  0  0  0  0  0  0  0  3  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  2  0  0  0  0  0
Camila Fernanda Guerrero Bustamante           3     | Construcción Civil                  |  1  0  0  0  0  0  0  0  0  0  2  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0
Simón Josías Cristóbal Álvarez Díaz           4     | Otras                               |  2  3  0  1  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0
Fernanda Ivonne Viera Castillo                5     | Constr

In [100]:
print(matriz_preferencias)

[[1, 0, 0, 0, 0, 0, 0, 0, 3, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 2, 0, 0, 0, 0, 0], [1, 0, 0, 0, 0, 0, 0, 0, 3, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 2, 0, 0, 0, 0, 0], [1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 2, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0], [2, 3, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0], [1, 0, 0, 0, 2, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 3, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0], [3, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 2, 0, 0, 0], [3, 0, 2, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0], [0, 1, 0, 0, 0, 0, 0, 0, 0, 3, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 2, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0], [0, 2, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0

### algoritmo

In [82]:
# parametros

cantidad_estudiantes = len(datos_estudiantes)
cantidad_desafios = len(datos_desafios)
capacidad_desafio = 3

In [89]:
cantidad_desafios

38

In [90]:
def distribucion_estudiantes(asignaciones, preferencias, capacidad_desafio):
    
    asignaciones_array = np.array(asignaciones)
    preferencias_array = np.array(preferencias)

    """
    num_estudiantes = asignaciones_array.shape[0]
    num_desafios = asignaciones_array.shape[1]
    """ 
    for estudiante in range(cantidad_estudiantes):
        # Verificar si el estudiante ya está asignado
        if np.sum(asignaciones_array[estudiante, :]) > 0:
            continue
        
        # Iterar sobre las preferencias del estudiante
        for preferencia in range(1, cantidad_desafios + 1):
            #desafio_preferido = np.where(preferencias[estudiante] == preferencia)[0][0]
            indices_preferido = np.where(preferencias[estudiante] == preferencia)[0]
            if indices_preferido.size > 0:  # Verifica si se encontró al menos un índice
                desafio_preferido = indices_preferido[0]
        # Aquí puedes continuar con la lógica para asignar el desafío
            else:
                continue
            
            # Verificar si el desafío aún tiene capacidad
            if np.sum(asignaciones[:, desafio_preferido]) < capacidad_desafio:
                return [estudiante, desafio_preferido]
    
    # Si no se puede asignar ningún estudiante a ningún desafío, devolver None
    return None

# Usar las matrices asignaciones y preferencias directamente
accion = distribucion_estudiantes(matriz_asignaciones, matriz_preferencias, capacidad_desafio)


C:\Users\salb7\AppData\Local\Temp\ipykernel_28384\3371692585.py:18: DeprecationWarning: Calling nonzero on 0d arrays is deprecated, as it behaves surprisingly. Use `atleast_1d(cond).nonzero()` if the old behavior was intended. If the context of this warning is of the form `arr[nonzero(cond)]`, just use `arr[cond]`.
  indices_preferido = np.where(preferencias[estudiante] == preferencia)[0]


In [86]:
def distribucion_estudiantes(asignaciones, preferencias, capacidad_desafio):
    asignaciones_array = np.array(asignaciones)
    preferencias_array = np.array(preferencias)

    for estudiante in range(len(asignaciones_array)):  # O cantidad_estudiantes
        # Verificar si el estudiante ya está asignado
        if np.sum(asignaciones_array[estudiante, :]) > 0:
            continue
        
        # Iterar sobre las preferencias del estudiante
        for preferencia in range(1, cantidad_desafios + 1):
            indices_preferido = np.where(preferencias_array[estudiante] == preferencia)[0]
            if indices_preferido.size > 0:
                desafio_preferido = indices_preferido[0]
                # Verificar si el desafío aún tiene capacidad
                if np.sum(asignaciones_array[:, desafio_preferido]) < capacidad_desafio:
                    return [estudiante, desafio_preferido]
    
    # Si no se puede asignar ningún estudiante a ningún desafío, devolver None
    return None

# Usar las matrices asignaciones y preferencias directamente
accion = distribucion_estudiantes(matriz_asignaciones, matriz_preferencias, capacidad_desafio)


In [98]:
def distribucion_estudiantes(asignaciones, preferencias, capacidad_desafio):
    asignaciones_array = np.array(asignaciones)
    preferencias_array = np.array(preferencias)

    num_estudiantes = asignaciones_array.shape[0]
    num_desafios = asignaciones_array.shape[1]
    
    # Lista para almacenar las asignaciones
    resultado_asignaciones = []

    for estudiante in range(num_estudiantes):
        # Verificar si el estudiante ya está asignado
        if np.sum(asignaciones_array[estudiante, :]) > 0:
            continue
        
        # Iterar sobre las preferencias del estudiante
        for preferencia in range(1, cantidad_desafios + 1):
            indices_preferido = np.where(preferencias[estudiante] == preferencia)[0]
            if indices_preferido.size > 0:  # Verifica si se encontró al menos un índice
                desafio_preferido = indices_preferido[0]

                # Verificar si el desafío aún tiene capacidad
                if np.sum(asignaciones[:, desafio_preferido]) < capacidad_desafio:
                    # Asignar estudiante al desafío
                    asignaciones_array[estudiante, desafio_preferido] = 1  # Puedes cambiarlo si usas otra forma de marcar la asignación
                    resultado_asignaciones.append((estudiante, desafio_preferido))  # Guarda la asignación
                    break  # Sale del bucle una vez que se asigna al estudiante

    # Comprobar si todos los estudiantes fueron asignados
    todos_asignados = len(resultado_asignaciones) == num_estudiantes

    return resultado_asignaciones, todos_asignados

# Usar las matrices asignaciones y preferencias directamente
accion, distribucion_completa = distribucion_estudiantes(matriz_asignaciones, matriz_preferencias, capacidad_desafio)
print(accion)
if distribucion_completa:
    print("La distribución se completó exitosamente.")
else:
    print("No todos los estudiantes fueron asignados a desafíos.")


[]
No todos los estudiantes fueron asignados a desafíos.


C:\Users\salb7\AppData\Local\Temp\ipykernel_28384\2952253787.py:18: DeprecationWarning: Calling nonzero on 0d arrays is deprecated, as it behaves surprisingly. Use `atleast_1d(cond).nonzero()` if the old behavior was intended. If the context of this warning is of the form `arr[nonzero(cond)]`, just use `arr[cond]`.
  indices_preferido = np.where(preferencias[estudiante] == preferencia)[0]


In [97]:
for i, estudiante in enumerate(datos_estudiantes):     
    print(f"|  {'  '.join(map(str, matriz_asignaciones[i]))}") 

|  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0
|  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0
|  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0
|  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0
|  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0
|  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0
|  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0
|  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0
|  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  

In [99]:
import numpy as np

def distribucion_estudiantes(asignaciones, preferencias, capacidad_desafio):
    asignaciones_array = np.array(asignaciones)
    preferencias_array = np.array(preferencias)

    num_estudiantes = asignaciones_array.shape[0]
    num_desafios = asignaciones_array.shape[1]
    
    # Lista para almacenar las asignaciones
    resultado_asignaciones = []

    for estudiante in range(num_estudiantes):
        # Verificar si el estudiante ya está asignado
        if np.sum(asignaciones_array[estudiante, :]) > 0:
            continue
        
        # Iterar sobre las preferencias del estudiante
        for preferencia in range(1, cantidad_desafios + 1):
            indices_preferido = np.where(preferencias[estudiante] == preferencia)[0]
            if indices_preferido.size > 0:  # Verifica si se encontró al menos un índice
                desafio_preferido = indices_preferido[0]

                # Verificar si el desafío aún tiene capacidad
                if np.sum(asignaciones_array[:, desafio_preferido]) < capacidad_desafio:
                    # Asignar estudiante al desafío
                    asignaciones_array[estudiante, desafio_preferido] = 1  # Marca la asignación
                    resultado_asignaciones.append((estudiante, desafio_preferido))  # Guarda la asignación
                    print(f"Asignado: Estudiante {estudiante} a Desafío {desafio_preferido}")  # Depuración
                    break  # Sale del bucle una vez que se asigna al estudiante

    # Comprobar si todos los estudiantes fueron asignados
    todos_asignados = len(resultado_asignaciones) == num_estudiantes

    return asignaciones_array, resultado_asignaciones, todos_asignados

# Usar las matrices asignaciones y preferencias directamente
matriz_asignaciones, accion, distribucion_completa = distribucion_estudiantes(matriz_asignaciones, matriz_preferencias, capacidad_desafio)

# Mostrar resultados
print("Matriz de asignaciones:")
print(matriz_asignaciones)
print("Acciones realizadas:", accion)
if distribucion_completa:
    print("La distribución se completó exitosamente.")
else:
    print("No todos los estudiantes fueron asignados a desafíos.")


Matriz de asignaciones:
[[0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 ...
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]]
Acciones realizadas: []
No todos los estudiantes fueron asignados a desafíos.


C:\Users\salb7\AppData\Local\Temp\ipykernel_28384\4181303719.py:20: DeprecationWarning: Calling nonzero on 0d arrays is deprecated, as it behaves surprisingly. Use `atleast_1d(cond).nonzero()` if the old behavior was intended. If the context of this warning is of the form `arr[nonzero(cond)]`, just use `arr[cond]`.
  indices_preferido = np.where(preferencias[estudiante] == preferencia)[0]


In [1]:
import copy
from collections import defaultdict

class TeamAssignment:
    def __init__(self, students, challenges, careers):
        self.students = students
        self.challenges = challenges
        self.careers = {career['Nombre']: career['Maximo'] for career in careers}
        self.assignments = defaultdict(list)
        self.student_assignments = {}

    def can_add_to_team(self, challenge, student):
        current_team = self.assignments[challenge]

        # Verificar tamaño máximo del equipo
        if len(current_team) >= 4:
            return False

        # Contar estudiantes por carrera en el equipo actual
        career_count = defaultdict(int)
        for member in current_team:
            career_count[member['Carrera']] += 1

        # Verificar restricciones de carrera según la configuración
        student_career = student['Carrera']
        max_allowed = self.careers.get(student_career, 1)  # Por defecto 1 si no está especificado

        if career_count[student_career] >= max_allowed:
            return False

        return True

    def initial_assignment(self):
        # Primera fase: asignar por primera preferencia
        for student in self.students:
            if len(student['Postulaciones']) > 0:
                first_choice = student['Postulaciones'][0]
                if self.can_add_to_team(first_choice, student):
                    self.assignments[first_choice].append(student)
                    self.student_assignments[student['Nombre']] = first_choice

    def find_best_team_for_student(self, student, exclude_challenge=None):
        best_team = None
        best_score = float('-inf')

        for challenge, team in self.assignments.items():
            if challenge == exclude_challenge:
                continue

            if len(team) < 4 and self.can_add_to_team(challenge, student):
                # Calcular score basado en preferencias y tamaño del equipo
                score = 0
                if challenge in student['Postulaciones']:
                    score += (3 - student['Postulaciones'].index(challenge)) * 2
                if len(team) == 1:  # Priorizar equipos que necesitan un miembro más
                    score += 3
                if len(team) == 2:  # También bueno para equipos de 2
                    score += 1

                if score > best_score:
                    best_score = score
                    best_team = challenge

        return best_team

    def resolve_single_member_teams(self):
        while True:
            single_member_teams = [(challenge, team) for challenge, team in self.assignments.items()
                                 if len(team) == 1]

            if not single_member_teams:
                break

            for challenge, team in single_member_teams:
                student = team[0]
                new_team = self.find_best_team_for_student(student, challenge)

                if new_team:
                    # Mover estudiante al nuevo equipo
                    self.assignments[challenge].remove(student)
                    self.assignments[new_team].append(student)
                    self.student_assignments[student['Nombre']] = new_team
                else:
                    # Si no se encuentra equipo, intentar traer otro estudiante a este equipo
                    found_teammate = False
                    for other_challenge, other_team in self.assignments.items():
                        if other_challenge != challenge and len(other_team) > 2:
                            for potential_teammate in other_team:
                                if self.can_add_to_team(challenge, potential_teammate):
                                    other_team.remove(potential_teammate)
                                    self.assignments[challenge].append(potential_teammate)
                                    self.student_assignments[potential_teammate['Nombre']] = challenge
                                    found_teammate = True
                                    break
                        if found_teammate:
                            break

            # Limpiar equipos vacíos
            self.assignments = {k: v for k, v in self.assignments.items() if len(v) > 0}

    def balance_teams(self):
        # Segunda fase: balancear equipos
        changes_made = True
        while changes_made:
            changes_made = False

            # Revisar equipos grandes (más de 4 estudiantes)
            for challenge, team in list(self.assignments.items()):
                if len(team) > 4:
                    # Intentar mover estudiantes excedentes a sus siguientes preferencias
                    for student in team[:]:
                        for pref in student['Postulaciones']:
                            if pref != challenge and self.can_add_to_team(pref, student):
                                team.remove(student)
                                self.assignments[pref].append(student)
                                self.student_assignments[student['Nombre']] = pref
                                changes_made = True
                                break

            # Resolver equipos con un solo miembro después de cada cambio
            self.resolve_single_member_teams()

    def force_assign_remaining(self):
        # Fase final: asignar estudiantes restantes
        unassigned = [s for s in self.students if s['Nombre'] not in self.student_assignments]

        for student in unassigned:
            best_team = self.find_best_team_for_student(student)

            if best_team:
                self.assignments[best_team].append(student)
                self.student_assignments[student['Nombre']] = best_team
            else:
                # Si no hay equipo disponible, crear nuevo equipo con otro estudiante no asignado
                remaining_unassigned = [s for s in unassigned if s != student and s['Nombre'] not in self.student_assignments]

                for other_student in remaining_unassigned:
                    # Buscar un desafío donde ambos estudiantes puedan estar juntos
                    for challenge in self.challenges:
                        if (self.can_add_to_team(challenge['Titulo'], student) and
                            self.can_add_to_team(challenge['Titulo'], other_student)):
                            self.assignments[challenge['Titulo']].extend([student, other_student])
                            self.student_assignments[student['Nombre']] = challenge['Titulo']
                            self.student_assignments[other_student['Nombre']] = challenge['Titulo']
                            break

    def run_assignment(self):
        self.initial_assignment()
        self.resolve_single_member_teams()
        self.balance_teams()
        self.force_assign_remaining()
        return self.assignments, self.student_assignments

    def print_assignment_stats(self):
        print("\nEstadísticas de asignación:")
        all_valid = True

        for challenge, team in self.assignments.items():
            print(f"\nDesafío: {challenge}")
            print(f"Número de estudiantes: {len(team)}")

            if len(team) < 2:
                print("⚠️ ERROR: Equipo con menos de 2 estudiantes")
                all_valid = False
            elif len(team) > 4:
                print("⚠️ ERROR: Equipo con más de 4 estudiantes")
                all_valid = False

            career_count = defaultdict(int)
            for student in team:
                career_count[student['Carrera']] += 1

            print("Distribución por carrera:")
            for career, count in career_count.items():
                max_allowed = self.careers.get(career, 1)
                print(f"- {career}: {count} (máximo permitido: {max_allowed})")
                if count > max_allowed:
                    print(f"⚠️ ERROR: Excede el máximo permitido para {career}")
                    all_valid = False

            print("Estudiantes en el equipo:")
            for student in team:
                print(f"- {student['Nombre']} ({student['Carrera']}): {student['Postulaciones']}")

        if all_valid:
            print("\n✅ Todas las asignaciones cumplen con las restricciones")
        else:
            print("\n❌ Hay asignaciones que no cumplen con las restricciones")

        # Mostrar estudiantes sin asignar
        unassigned = self.get_unassigned_students()
        if unassigned:
            print("\n⚠️ Estudiantes sin asignar:")
            for student in unassigned:
                print(f"- {student}")

    def get_unassigned_students(self):
        return [s['Nombre'] for s in self.students if s['Nombre'] not in self.student_assignments]